#!/usr/bin/perl -w
#----------------------------------------------------------------------
# vim: ts=4 sw=4 et:
#----------------------------------------------------------------------
# This file is part of the "Subversion repositories" panel in the
# SME Server server-manager panel to configure subversion repositories.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

#------------------------------------------------------------
# Delete the files for the repository.
#------------------------------------------------------------

use strict;
use Errno;
use File::Path;

use esmith::AccountsDB;
my $adb = esmith::AccountsDB->open_ro();

my $event = $ARGV [0];
my $repository = $ARGV [1];

$a = $adb->get($repository) || undef;
unless ( defined $a && $a->prop('type') eq "repository-deleted" )
{
    warn "$repository is not a repository\n";
    exit (0);
}

my $dir = "/home/e-smith/files/repositories/$repository";

exit 0 unless ( -d $dir );

rmtree( $dir ) || die "Couldn't remove tree $dir\n";

exit (0);
